// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// check_for_unknown_vars_impl
void check_for_unknown_vars_impl(List model, SEXP x);
RcppExport SEXP _ompr_check_for_unknown_vars_impl(SEXP modelSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type model(modelSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    check_for_unknown_vars_impl(model, x);
    return R_NilValue;
END_RCPP
}
// is_non_linear_impl
bool is_non_linear_impl(CharacterVector var_names, SEXP x);
RcppExport SEXP _ompr_is_non_linear_impl(SEXP var_namesSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type var_names(var_namesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(is_non_linear_impl(var_names, x));
    return rcpp_result_gen;
END_RCPP
}
