# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

is_non_linear_impl <- function(var_names, x) {
    .Call('ompr_is_non_linear_impl', PACKAGE = 'ompr', var_names, x)
}

